repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

- repo: local 
  hooks:
    - id: checks
      name: checks
      entry: tox run --
      language: system
      stages: [commit-msg]
